---
- name: Install some test packages
  hosts: test
  become: yes
  tasks:

  - name: Install package
    dnf:
      name:
        - httpd
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - screen
        - sysstat
      state: latest
