---
- name: Install some test packages
  hosts: test
  become: yes
  tasks:

  - name: Install httpd, epel & sysstat
    dnf:
      name:
        - httpd
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - sysstat
      state: present

  - name: Install screen
    dnf:
      name:
        - screen
      state: present
      
      
